import os
import re

import pandas as pd
import plotly.express as px
import streamlit as st


st.set_page_config(page_title="AIOps Anomaly Dashboard", layout="wide")

OUTPUT_DIR = "output"
CSV_FILES = {
    "all": os.path.join(OUTPUT_DIR, "my_log_analysis.csv"),
    "train": os.path.join(OUTPUT_DIR, "train_log_analysis.csv"),
    "test": os.path.join(OUTPUT_DIR, "test_log_analysis.csv"),
    "test_anomalies": os.path.join(OUTPUT_DIR, "test_suspicious_logs.csv"),
}


@st.cache_data
def load_csv(path):
    if not os.path.exists(path):
        return None
    frame = pd.read_csv(path)
    if "timestamp" in frame.columns:
        frame["timestamp"] = pd.to_datetime(frame["timestamp"], errors="coerce")
    return frame


def normalize_message_template(message):
    text = str(message)
    text = re.sub(r"\b(?:\d{1,3}\.){3}\d{1,3}\b", "<IP>", text)
    text = re.sub(r"\b\d+\b", "<NUM>", text)
    text = re.sub(r"\b(job|task|attempt|container)_\S+", r"\1_<ID>", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def safe_metric_delta(current_value, baseline_value):
    if baseline_value in (0, None):
        return None
    delta_pct = ((current_value - baseline_value) / baseline_value) * 100
    return f"{delta_pct:+.1f}%"


df_all = load_csv(CSV_FILES["all"])
df_train = load_csv(CSV_FILES["train"])
df_test = load_csv(CSV_FILES["test"])
df_test_anomalies = load_csv(CSV_FILES["test_anomalies"])

st.title("AIOps Log Analysis Dashboard")
st.caption("Interactive dashboard for anomaly outputs generated by aiops_log_analysis.py")

if df_all is None:
    st.error("Missing output/my_log_analysis.csv. Run aiops_log_analysis.py first.")
    st.stop()

df_all = df_all.copy()
df_all["is_anomaly"] = df_all["status"].astype(str).str.contains("Anomaly", na=False)
df_all["message_template"] = df_all["message"].map(normalize_message_template)

st.sidebar.header("Filters")
levels = sorted(df_all["level"].dropna().unique().tolist())
selected_levels = st.sidebar.multiselect("Severity levels", levels, default=levels)
split_options = ["all"]
if "split" in df_all.columns:
    split_options.extend(sorted(df_all["split"].dropna().unique().tolist()))
selected_split = st.sidebar.selectbox("Dataset split", split_options)
anomalies_only = st.sidebar.checkbox("Show anomalies only", value=False)
selected_loggers = st.sidebar.multiselect(
    "Logger namespaces",
    sorted(df_all["logger"].dropna().unique().tolist()),
    default=[],
)

filtered_df = df_all[df_all["level"].isin(selected_levels)].copy()
if selected_split != "all" and "split" in filtered_df.columns:
    filtered_df = filtered_df[filtered_df["split"] == selected_split]
if anomalies_only:
    filtered_df = filtered_df[filtered_df["is_anomaly"]]
if selected_loggers:
    filtered_df = filtered_df[filtered_df["logger"].isin(selected_loggers)]

if filtered_df.empty:
    st.warning("No rows match the current filters.")
    st.stop()

total_logs = len(filtered_df)
anomaly_count = int(filtered_df["is_anomaly"].sum())
anomaly_rate = (anomaly_count / total_logs) * 100 if total_logs else 0
error_like_count = len(filtered_df[filtered_df["level"].isin(["ERROR", "CRITICAL", "FATAL"])])

train_rate = None
test_rate = None
if df_train is not None and "status" in df_train.columns:
    train_rate = df_train["status"].astype(str).str.contains("Anomaly", na=False).mean() * 100
if df_test is not None and "status" in df_test.columns:
    test_rate = df_test["status"].astype(str).str.contains("Anomaly", na=False).mean() * 100

metric_cols = st.columns(4)
metric_cols[0].metric("Filtered log rows", f"{total_logs}")
metric_cols[1].metric("Anomaly count", f"{anomaly_count}")
metric_cols[2].metric("Anomaly rate", f"{anomaly_rate:.1f}%")
metric_cols[3].metric(
    "High severity rows",
    f"{error_like_count}",
    delta=safe_metric_delta(anomaly_rate, train_rate) if train_rate is not None and selected_split == "test" else None,
)

overview_col, split_col = st.columns([2, 1])

with overview_col:
    st.subheader("Anomaly Volume Over Time")
    timeline_df = filtered_df.set_index("timestamp").resample("1min").size().rename("log_count").reset_index()
    anomaly_timeline_df = (
        filtered_df[filtered_df["is_anomaly"]]
        .set_index("timestamp")
        .resample("1min")
        .size()
        .rename("anomaly_count")
        .reset_index()
    )
    merged_timeline = timeline_df.merge(anomaly_timeline_df, on="timestamp", how="left").fillna(0)
    fig_timeline = px.line(
        merged_timeline,
        x="timestamp",
        y=["log_count", "anomaly_count"],
        title="Log Volume vs Anomalies Per Minute",
        markers=True,
    )
    fig_timeline.update_layout(legend_title_text="Series")
    st.plotly_chart(fig_timeline, use_container_width=True)

with split_col:
    st.subheader("Anomaly Rate by Split")
    if "split" in df_all.columns:
        split_stats = (
            df_all.groupby("split", as_index=False)["is_anomaly"]
            .mean()
            .rename(columns={"is_anomaly": "anomaly_rate"})
        )
        split_stats["anomaly_rate"] = split_stats["anomaly_rate"] * 100
        fig_split = px.bar(
            split_stats,
            x="split",
            y="anomaly_rate",
            color="split",
            title="Train vs Test Anomaly Rate",
            text="anomaly_rate",
        )
        fig_split.update_traces(texttemplate="%{text:.1f}%", textposition="outside")
        fig_split.update_layout(showlegend=False)
        st.plotly_chart(fig_split, use_container_width=True)
    else:
        st.info("Split column not present in the current analysis output.")

level_col, logger_col = st.columns(2)

with level_col:
    st.subheader("Anomaly Count by Severity")
    level_counts = filtered_df[filtered_df["is_anomaly"]]["level"].value_counts().reset_index()
    level_counts.columns = ["level", "count"]
    if level_counts.empty:
        st.info("No anomalies available for the current filters.")
    else:
        fig_levels = px.bar(
            level_counts,
            x="level",
            y="count",
            color="level",
            title="Anomaly Count by Severity Level",
            text="count",
        )
        st.plotly_chart(fig_levels, use_container_width=True)

with logger_col:
    st.subheader("Top Logger Namespaces")
    logger_counts = (
        filtered_df[filtered_df["is_anomaly"]]["logger"]
        .value_counts()
        .head(12)
        .reset_index()
    )
    logger_counts.columns = ["logger", "count"]
    if logger_counts.empty:
        st.info("No anomalous logger namespaces found.")
    else:
        fig_loggers = px.bar(
            logger_counts,
            x="count",
            y="logger",
            orientation="h",
            title="Top Logger Namespaces Among Anomalies",
            text="count",
        )
        fig_loggers.update_layout(yaxis={"categoryorder": "total ascending"})
        st.plotly_chart(fig_loggers, use_container_width=True)

pattern_col, interactive_col = st.columns(2)

with pattern_col:
    st.subheader("Repeated Anomaly Templates")
    template_counts = (
        filtered_df[filtered_df["is_anomaly"]]["message_template"]
        .value_counts()
        .head(12)
        .reset_index()
    )
    template_counts.columns = ["message_template", "count"]
    if template_counts.empty:
        st.info("No repeated anomaly templates available.")
    else:
        fig_templates = px.bar(
            template_counts,
            x="count",
            y="message_template",
            orientation="h",
            title="Top Repeated Anomaly Templates",
            text="count",
        )
        fig_templates.update_layout(yaxis={"categoryorder": "total ascending"})
        st.plotly_chart(fig_templates, use_container_width=True)

with interactive_col:
    st.subheader("Interactive Anomaly Event Timeline")
    event_df = filtered_df[filtered_df["is_anomaly"]].copy()
    if event_df.empty:
        st.info("No anomalies available for interactive timeline.")
    else:
        event_df["short_message"] = event_df["message"].astype(str).str.slice(0, 140)
        fig_events = px.scatter(
            event_df.sort_values("timestamp"),
            x="timestamp",
            y="logger",
            color="level",
            hover_data=["thread", "short_message", "explanation"],
            title="Anomaly Events by Logger",
            height=550,
        )
        st.plotly_chart(fig_events, use_container_width=True)

st.subheader("Detailed Rows")
display_columns = [
    column for column in [
        "timestamp",
        "split",
        "level",
        "logger",
        "thread",
        "message",
        "status",
        "explanation",
        "if_score",
        "zscore_max",
    ]
    if column in filtered_df.columns
]
st.dataframe(filtered_df[display_columns], use_container_width=True, height=420)

if df_test_anomalies is not None and not df_test_anomalies.empty:
    st.subheader("Test Split Anomaly Sample")
    st.dataframe(df_test_anomalies.head(25), use_container_width=True)